# ----------------------
# Git Aliases
# ----------------------
alias gita='git add'
alias gitaa='git add .'
alias gitaaa='git add -A'
alias gitb='git branch'
alias gitbd='git branch -d '
alias gitc='git commit'
alias gitcm='git commit -m'
alias gitcma='git commit -a -m'
alias gitco='git checkout'
alias gitcob='git checkout -b'
alias gitcom='git checkout master'
alias gitd='git diff'
alias gitda='git diff HEAD'
alias giti='git init'
alias gitl='git log'
alias gitlg='git log --graph --oneline --decorate --all'
alias gitld='git log --pretty=format:"%h %ad %s" --date=short --all'
alias gitm='git merge --no-ff'
alias gitp='git pull'
alias gitss='git status -s'
alias gitst='git stash'
alias gitstl='git stash list'
alias gitstp='git stash pop'
alias gitstd='git stash drop'
